version: "3.2"

services:
  inspector:
    build:
      context: .

    container_name: "instagram-inspector"
    image: "instagram-inspector"
    command: "python main.py"
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: ./database.sqlite3
        target: /app/database.sqlite3
      - ./logs/*:/app/logs/*
    env_file:
      - .env

volumes:
  database:
    driver: local

